### ISSUE TITLE
Question: Is it possible to get the frequency to display with more precision?

### ISSUE THREAD

**Issue by wiccan2** [florentbr/OWON-VDS1022#18]
The UI currently shows frequencies to two decimal places (e.g. 14.08), is it possible to configure this to show more decimal places (e.g. 14.0740)?

**Comment by florentbr** [comment]
With a selected timebase maximizing the signal period over the 5k samples, the maximum precision would be 0.0028 Hz (14Hz / 5000). The precision drops to 0.005Hz if the period is half the screen and 0.011Hz if it is on 1/4. Rounding to 2 decimals seems reasonable since it hides the error in the rounding. I don't really see the value in changing the displayed precision if it's to display a reading error. Unless I'm missing something?
