### ISSUE TITLE
sec/div centered in dropdown

### ISSUE THREAD

**Issue by ericdurfee** [florentbr/OWON-VDS1022#44]
I mostly use a mouse. Would be nice if when clicking on time/div, the current setting was in the middle of the dropdown. Then I wouldn't have to scroll to change the sweep to 10x faster.

**Comment by florentbr** [comment]
I agree, the Combobox is not very handy. It's a Java component with no direct way to set the scrolling position.
It would require to create a new component which is not a trivial thing.

At some point I thought of adding some gestures on the chart :
Double click/tap left : reduce the timebase
Double click/tap right : increase the timebase

But since I only use shortcuts (+,-), I never implemented it.

Have you tried to scroll the timebase directly without clicking on it?
If I remember correctly, scrolling directly on a setting will set the next/previous value.

**Comment by ericdurfee** [comment]
Thanks. Scrolling time base worked great, after I cleaned the mouse wheel.

    On Monday, January 3, 2022, 05:57:31 AM CST, Florent ***@***.***> wrote:  
 
 


I agree, the Combobox is not very handy. It's a Java component with no direct way to set the scrolling position.
It would require to create a new component which is not a trivial thing.

At some point I thought of adding some gestures on the chart :
Double click/tap left : reduce the timebase
Double click/tap right : increase the timebase

But since I only use shortcuts (+,-), I never implemented it.

Have you tried to scroll the timebase directly without clicking on it?
If I remember correctly, scrolling directly on a setting will set the next/previous value.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
