### ISSUE TITLE
UI improvements for full screen X-Y and FFT

### ISSUE THREAD

**Issue by csdpm** [florentbr/OWON-VDS1022#55]
Hi Florent,

Many thanks for the new full screen X-Y display... and the very welcome bonus of full screen FFT display too, it finally makes the FFT capability worthwhile!  I have a 'feature report and UI suggestion.

'Feature' report:
In default scope state (no X-Y or FFT enabled) clicking on the main screen 'To Three view' button displays split screen Scope and X-Y display view, but no signal is displayed in the X-Y portion. Can I suggest either disabling the split screen when neither X-Y nor FFT is selected, or alternatively, maybe automatically enabling X-Y mode under this condition. This sounds more complicated for you, as full screen X-Y would also need to be available at that point (finding full screen X-Y caused a little confusion in the eevblog VDS1022i thread yesterday). Whichever works best for you.

UI suggestion:
With your new Full screen features, when either X-Y or FFT is enabled, clicking on the 'To Three view' button toggles between full screen and split screen with scope display. It would be helpful if this was a 3 way toggle...
Full screen X-Y (or FFT) ->Split screen X-Y (or FFT) -> Full screen scope display.
This would also save you having to change the 'Three View' help text :-)

I briefly wondered if it would be worth extending to some sort of X-Y Full -> X-Y split -> FFT Full -> split etc. but I think this would involve far too many combinations. In FFT mode, the FFT (Math) menu needs to be used a lot anyway, and the user is very unlikely to (never?) be doing something that involves both X-Y and FFT at the same time.

I hope this helps,
Chris (gyro)

**Comment by florentbr** [comment]
> Many thanks for the new full screen X-Y display... and the very welcome bonus of full screen FFT display too, it finally makes the FFT capability worthwhile!

The full FFT screen was already there with the original software. It's just "full width" now when in split view. I was annoyed by this tiny FFT view especially since the XY mode is not supposed to work when the FFT is on. Not to mention that in 3 splits view, the X axis of the XY mode was wider than the Y axis.

> Can I suggest either disabling the split screen when neither X-Y nor FFT is selected, or alternatively, maybe automatically enabling X-Y mode under this condition

I originally wanted to automatically turn on the XY mode when the "3 views" mode is activated and only if the FFT is off. But then as you mentioned another click would turn the full XY view when one (maybe just me) would expect it to revert back to a single view with XY mode disabled. So I left it at that. I agree, a 3 state click would work and be more interesting than just disabling the button. Though I'd give it a different order:  

**FFT ON:** Split channels / FFT -> Full FFT -> Split channels / FFT
**FFT OFF:** Full channels -> Split channels with XY to ON -> Full XY -> Full channels



>  the user is very unlikely to (never?) be doing something that involves both X-Y and FFT at the same time.

The FFT mode with the original software only allows 1 channel at a time. I think it was designed that way to give the buffer of the second channel to the processing of the FFT. But to my surprise the FFT is not even performed by the FPGA but by the software itself. So with the VDS1022, it's technically possible to have 2 channels, 2 FFT and the XY mode at the same time. If a user needs the 3 of them at the same time, he is either using the wrong device or doing something impractical. The only improvement in this area I can see would be to add the Gain and Phase shift between channel 1 and 2 on the time domain. But I'm quite confident that it would never be used.

**Comment by Trace-2** [comment]
Hi Florent it was me that originally requested the full screen XY and very happy now (I will send you a donation) FFT is also much better ... :)

I'm up for the 3 state click too ... the Three View button kind of suggests that is the function , that's why I originally wondered if I was just doing something wrong with it and not getting the 3rd view.

Thanks for your time ... very happy with the software ... :)

**Comment by csdpm** [comment]
> FFT ON: Split channels / FFT -> Full FFT -> Split channels / FFT
> FFT OFF: Full channels -> Split channels with XY to ON -> Full XY -> Full channels

Yes, that sounds fine. The only real reason for being able to see the channels in FFT mode is to be able to check that the input isn't clipping.

Thanks again!

**Comment by florentbr** [comment]
implemented in release 1.1.3-cf18
